### ISSUE TITLE
Can not get token after calling InstanceID.deleteToken() 

### ISSUE THREAD

**Issue by NeoLSN** [VictorAlbertos/RxGcm#10]
`RxGcm.Notifications.currentToken()` will fail after doing `InstanceID.deleteToken()`.

Can you add a refresh token mechanism in the `RxGcm.Notifications.currentToken()`?

**Comment by VictorAlbertos** [comment]
I'll check this the next week. 

But, in the meantime,  can you try to call `register` again, before calling `RxGcm.Notifications.currentToken()`, and let me know if after doing that calling `RxGcm.Notifications.currentToken()` returns a valid token?

**Comment by NeoLSN** [comment]
Yes, it returns a valid token after calling `register` again.

I have a suggestion about this.
For most of time, the broadcast receiver and the background broadcast receiver will not change in app.
Calling `register` again is a little inconvenience.
I think it will be very helpful if there is a refresh/reset token method can be called.

**Comment by VictorAlbertos** [comment]
I think calling register again is the logical step to do. 

```
RxGcm.Notifications.register(this, AppGcmReceiverData.class, AppGcmReceiverUIBackground.class)
                .subscribe(token -> {}, error -> {});
```

Plus, they are just two lines ;)

I'm going to close the issue, but if you have further questions please feel free to reopen it.
