### ISSUE TITLE
RxGcm.Notifications.register throws IOException INVALID_PARAMETERS

### ISSUE THREAD

**Issue by canpoyrazoglu** [VictorAlbertos/RxGcm#11]
My `register` method fails with an IOException which only says `INVALID_PARAMETERS`. Why would I be getting this error? I've included the `google-services.json` that I've downloaded on `app` directory, and GCM is enabled in Google Cloud console.

**Comment by VictorAlbertos** [comment]
Hi.

I found this [info](http://stackoverflow.com/questions/16471209/in-gcm-what-is-the-error-id-in-onerror-context-context-string-errorid) about the error:

```
INVALID_PARAMETERS

The request sent by the phone does not contain the expected parameters. This phone doesn't currently support GCM.
```

Are you trying to register from an android emulator? In any case, it seems the error is caused by the device, more than RxGcm itself.

**Comment by canpoyrazoglu** [comment]
Hello,

I've seen that. No I'm trying from an actual device that can receive push notifications from other apps perfectly, running on Android 4.4.4.

Yeah it seems that it's device-related, but maybe a configuration error causes it? I did perform all the steps in readme though.

**Comment by canpoyrazoglu** [comment]
Hello again,

I've dug in deeper, and the error seems to be caused by:

`return instanceID.getToken(context.getString(string.gcm_defaultSenderId), "GCM", (Bundle)null);` on `GetGcmServerToken`:

<img width="1186" alt="screen shot 2016-05-02 at 08 53 32" src="https://cloud.githubusercontent.com/assets/4348413/14947938/665bc95c-1043-11e6-9e1a-29eec8c4a3d4.png">

I can navigate to and inspect `string.gcm_defaultSenderId` though, it's a valid string. After that, an `IOException` is thrown with `INVALID_PARAMETERS`. I am not the master of it but to me it seems like a configuration issue.

**Comment by VictorAlbertos** [comment]
Hi @canpoyrazoglu 

Can you upload a project to Github which replicates the issue in order to take a look on it?

Thanks.

**Comment by canpoyrazoglu** [comment]
Hello again,

I just rechecked (sorry for the late reply) my project and I've realized that while I was trying to solve this other closed issue of mine (https://github.com/VictorAlbertos/RxGcm/issues/9) I accidentally removed the apply Google Play plugin command (for completeness sake, this is what I've added to my _app_s gradle: `apply plugin: 'com.google.gms.google-services'`). I've added it back and now it compiles. Maybe it would be nice to handle this situation like throwing an exception saying _"GCM default sender is not set, are you sure you have a valid google-services.json file and you've added the appropriate command to build.gradle to apply Google Services plugin?"_

Thank you anyway :)
