### ISSUE TITLE
NPE when another activity is in foreground

### ISSUE THREAD

**Issue by sonerd** [VictorAlbertos/RxGcm#12]
First thanks for this nice library. I have integrated it into my app. In my app I have a couple of activities. Only one activity is implementing `GcmReceiverUIForeground`. When the user is actually on another activity screen and a notification is received a NPE is thrown in class `RxGcm` line number 174 cause `wrapperGcmReceiverUIForeground` is null. The workaround I see is to let all my activities implement `GcmReceiverUIForeground`. Or is there another solution?

**Comment by VictorAlbertos** [comment]
Hi @sonerd :)

Just to clarify, are you using the last version of RxGcm?

`compile 'com.github.VictorAlbertos:RxGcm:0.2.2'`

**Comment by sonerd** [comment]
No, I am using `0.2.1`

**Comment by sonerd** [comment]
I just saw that you have fixed in `0.2.2` 👍  I will try it out.

**Comment by sonerd** [comment]
It works. Thanks 👍
