### ISSUE TITLE
Firebase cloud messaging 

### ISSUE THREAD

**Issue by ReginFell** [VictorAlbertos/RxGcm#16]
Hi!

Are you going to support FCM in RxGcm ?

**Comment by VictorAlbertos** [comment]
Hi @ReginFell I need to think about it.

It seems that [Google itself suggests](https://developers.google.com/cloud-messaging/faq) to use FCM for new applications:

> Is GCM going to be deprecated?
> 
> We will continue to support the current version of GCM Android and iOS SDKs because we know a lot of developers are using GCM SDKs today to handle notifications, and client app upgrade takes time.
> 
> But all new client-side features will be added to FCM SDKs only moving forward. You are strongly encouraged to upgrade to FCM SDKs.

So, one way or another I will need to give support for FCM eventually. But I don't know if by creating an abstraction layer and splitting the current library into several modules sharing a same core module, or by creating a new complete library. It will depend on how much business login could be reused between [FCM  and GCM implementations](https://developers.google.com/cloud-messaging/android/android-migrate-fcm).

**Comment by VictorAlbertos** [comment]
Hi @ReginFell. 

I deprecated RxGcm library. From now on you should use [RxFcm](https://github.com/VictorAlbertos/RxFcm) library instead ;)

**Comment by zabelnikov** [comment]
Amazing work, thanks!

**Comment by ReginFell** [comment]
Amazing work, thanks!

**Comment by mmotorniy** [comment]
@VictorAlbertos You are awesome! Thanks a lot!

**Comment by VictorAlbertos** [comment]
@ReginFell @mmotorniy You're welcome. And thanks for the feedback ;)
