### ISSUE TITLE
Does GCM receiver's category name should be changed to ${applicationId} in AndroidManifest.xml?

### ISSUE THREAD

**Issue by NeoLSN** [VictorAlbertos/RxGcm#2]
Follow the example from [official document](https://developers.google.com/cloud-messaging/android/client).
the example

```
     <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="com.example.gcm" />
            </intent-filter>
        </receiver>
```

Should category name be changed to ${applicationId}?

```
<category android:name="${applicationId}" />
```

**Comment by VictorAlbertos** [comment]
You should not change the manifest. The library does all that configuration work for you.

**Comment by NeoLSN** [comment]
Sorry, I may let you be confused.
I know I should not change the manifest.
[My question is in here](https://github.com/VictorAlbertos/RxGcm/blob/master/rx_gcm/src/main/AndroidManifest.xml#L28)
Should this category name be changed to like below?

```
<category android:name="${applicationId}" />
```

I just put a question in here, because I don't know should it be replaced to user project application id or I am thinking something wrong.

**Comment by VictorAlbertos** [comment]
No. It should not be replaced in the user project. You don't need to touch the manifest at all.
