### ISSUE TITLE
can RxGcm.Notifications.currentToken be called from anywhere?

### ISSUE THREAD

**Issue by thomasdola** [VictorAlbertos/RxGcm#3]
can `RxGcm.Notifications.currentToken` be called from anywhere like a simple java class.
not an activity or fragment.
and how can i link `RefreshTokenReceiver` that implements `GcmRefreshTokenReceiver` to the rest of the app; say , sending the token to rest of the app or calling a method and passing the refresh token as   an argument?
thanks..

**Comment by VictorAlbertos** [comment]
Hi.

Yes, you can call `RxGcm.Notifications.currentToken` from anywhere, as long as you've been called first `RxGcm.Notifications.register` in you Application class.

About your second question, I think it is not related with RxGcm itself. It's more about how you should architect your application. But when you implement the `GcmRefreshTokenReceiver` you can access to the Application class from the object received in `onTokenReceive` method (`TokenUpdate` holds a reference to the instance of Application), from there you can get the Context or whatever you need. Personally, I would hit a server to update the associated token. 

Just for clarify. You don't need to update the token locally, RxGcm do that for you. I mean, if the token requires to be updated from Gcm server, RxGcm save the new token in the device, that way when you call `RxGcm.Notifications.currentToken` you always get the last updated token. This method is meant to be used just to notify external services (like your back-end server) about this event.
