### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by canpoyrazoglu** [VictorAlbertos/RxGcm#9]
I'm trying to use RxGcm with my project but I'm getting:

Error:Execution failed for task ':app:processDebugGoogleServices'.

> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 8.3.0.

I've had a few components that were 8.4.0 and I've downgraded all of them to 8.3.0, but then I'm getting another error about mixing versions. I've done exactly what was written at https://github.com/VictorAlbertos/RxGcm#setup.

**Comment by VictorAlbertos** [comment]
Try to exclude the gcm dependency from RxGcm, and let me know ;)

``` gradle
    compile("com.github.VictorAlbertos:RxGcm:0.2.2") {
        exclude module: 'play-services-gcm'
    }
```

**Comment by canpoyrazoglu** [comment]
Now I started to get this, but I'm not sure if it's related or not:

```
Error:Error converting bytecode to dex: 
Cause: com.android.dex.DexException: Multiple dex files define Lcom/flurry/android/Constants;
```

**Comment by canpoyrazoglu** [comment]
It seems to be related to something completely (Flurry) but it may just be a a side-effect of something else so I'm not sure.

**Comment by canpoyrazoglu** [comment]
Oh it was just having Flurry's JAR **and** gradle dependency together (don't know how I ended that way). Now my project compiles correctly with your code:

```
compile("com.github.VictorAlbertos:RxGcm:0.2.2") {
    exclude module: 'play-services-gcm'
}
```

However, I currently don't have time to test to see if it runs correctly, but I think it will. Thank you :)
